In [1]:
import torch

x = torch.Tensor(5,3)
y = torch.rand(5,3)


In [2]:
x

tensor([[-6.6553e+26,  4.5825e-41, -6.3165e+26],
        [ 4.5825e-41, -3.1521e+31,  4.5825e-41],
        [-6.7079e+29,  4.5825e-41, -6.7080e+29],
        [ 4.5825e-41, -3.5693e+31,  4.5825e-41],
        [-3.7555e+31,  4.5825e-41, -1.6324e+31]])

In [3]:
y

tensor([[0.5696, 0.7353, 0.6681],
        [0.2231, 0.5104, 0.7211],
        [0.0647, 0.0485, 0.9268],
        [0.6744, 0.0932, 0.5624],
        [0.5250, 0.3532, 0.6301]])

In [4]:
x.size()
y.size()

torch.Size([5, 3])

In [5]:
x + y

tensor([[-6.6553e+26,  7.3532e-01, -6.3165e+26],
        [ 2.2307e-01, -3.1521e+31,  7.2105e-01],
        [-6.7079e+29,  4.8520e-02, -6.7080e+29],
        [ 6.7442e-01, -3.5693e+31,  5.6237e-01],
        [-3.7555e+31,  3.5321e-01, -1.6324e+31]])

In [6]:
y + x

tensor([[-6.6553e+26,  7.3532e-01, -6.3165e+26],
        [ 2.2307e-01, -3.1521e+31,  7.2105e-01],
        [-6.7079e+29,  4.8520e-02, -6.7080e+29],
        [ 6.7442e-01, -3.5693e+31,  5.6237e-01],
        [-3.7555e+31,  3.5321e-01, -1.6324e+31]])

In [7]:
x[:, 1]

tensor([ 4.5825e-41, -3.1521e+31,  4.5825e-41, -3.5693e+31,  4.5825e-41])

In [8]:
a  = torch.ones(5)


In [9]:
a


tensor([1., 1., 1., 1., 1.])

In [10]:
b = a.numpy()

In [11]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [12]:
a.add(1)

tensor([2., 2., 2., 2., 2.])

In [13]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [14]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [15]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [16]:
a

tensor([2., 2., 2., 2., 2.])

In [17]:
import numpy as np

In [18]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
torch.cuda.is_available()


False

In [21]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1   = nn.Linear(16*5*5, 120)
        self.fc2   = nn.Linear(120, 84)
        self.fc3   = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [22]:
params = list(net.parameters())
print(len(params))

10


In [23]:
print(params[0].size())

torch.Size([6, 1, 5, 5])


In [24]:
input = Variable(torch.randn(1, 1, 32, 32))

NameError: name 'Variable' is not defined

In [25]:
from torch.autograd import Variable
input = Variable(torch.randn(1, 1, 32, 32))
out = net(input)
net.zero_grad()
out.backward(torch.randn(1, 10))